### ISSUE TITLE
Add new crates.io aerospace categories

### ISSUE THREAD

**Issue by MoralCode** [KubOS-Preservation-Group/ccsds-spacepacket#13]
Thanks to @elpiel of the AeroRust comminity, new categories for aerospace apps have been approved to add to crates.io.

Once these have been merged into crates.io, we should update this crate to use the relevant categories

**Comment by elpiel** [comment]
I believe this was done in https://github.com/KubOS-Preservation-Group/ccsds-spacepacket/commit/2420c97784934e364953e09251496c340e43e355 ?

**Comment by MoralCode** [comment]
ah yes, forgot to link the issue
