### ISSUE TITLE
Handle reading and writing byte streams

### ISSUE THREAD

**Issue by MoralCode** [KubOS-Preservation-Group/ccsds-spacepacket#4]
Is this a common use case?

**Comment by MoralCode** [comment]
Since this is a packet protocol intended to be used over a network, i think this makes sense to use stream handling and partial parsing provided by `nom` as the default.

**Comment by wcampbell0x2a** [comment]
I usually use https://docs.rs/deku/0.12.4/deku/index.html for this, which allows streams of bytes. Deku returns an Incomplete error when not receiving the whole packet, and returns the bytes that weren't parsed in the `from_bytes` method.

**Comment by wcampbell0x2a** [comment]
Looking at this library, it would be a pretty good library for deku usage.

**Comment by MoralCode** [comment]
wow, thanks a ton for the suggestion, this looks like a great library to use! ive generally been hesitant to use libraries because the ones ive looked at so far (nom, serde) dont seem to be built for this usecase, but at first glance this looks pretty similar to how things are being done currently.

Thanks for the suggestion! Not sure when ill be able to get around to adding this but i'd be happy to look at a PR if you want to make one!

**Comment by MoralCode** [comment]
closed by #11. this crate can now theoretically handle byte streams
