### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by MoralCode** [KubOS-Preservation-Group/ccsds-spacepacket#8]
What will it take to get this to a reasonable state to publish on crates.io?

i think #1 is probably a good start, and possibly also documenting that this is so far just a primary header parser, not a full spacepacket parser

**Comment by elpiel** [comment]
I would say that you can publish it like this and later add examples & docs.
It can be useful for people if they are looking for it on crates.io and they just might help with the documentation. You can also try to add hacktoberfest and find contributors.

It's a long shot but you can always try :D

**Comment by MoralCode** [comment]
published as https://crates.io/crates/ccsds_spacepacket
